# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BilgiGüncellemeSayfası.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_guncelle(object):
    def setupUi(self, Form_guncelle):
        Form_guncelle.setObjectName("Form_guncelle")
        Form_guncelle.resize(400, 220)
        self.label = QtWidgets.QLabel(Form_guncelle)
        self.label.setGeometry(QtCore.QRect(40, 10, 331, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form_guncelle)
        self.label_2.setGeometry(QtCore.QRect(0, 70, 341, 16))
        self.label_2.setObjectName("label_2")
        self.groupBox = QtWidgets.QGroupBox(Form_guncelle)
        self.groupBox.setGeometry(QtCore.QRect(0, 120, 151, 41))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.radioButton_tc = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_tc.setGeometry(QtCore.QRect(0, 10, 95, 20))
        self.radioButton_tc.setObjectName("radioButton_tc")
        self.groupBox_2 = QtWidgets.QGroupBox(Form_guncelle)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 170, 151, 41))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton_isim = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_isim.setGeometry(QtCore.QRect(0, 10, 141, 20))
        self.radioButton_isim.setObjectName("radioButton_isim")

        self.retranslateUi(Form_guncelle)
        QtCore.QMetaObject.connectSlotsByName(Form_guncelle)

    def retranslateUi(self, Form_guncelle):
        _translate = QtCore.QCoreApplication.translate
        Form_guncelle.setWindowTitle(_translate("Form_guncelle", "Form"))
        self.label.setText(_translate("Form_guncelle", "ÖĞRENCİ BİLGİSİ GÜNCELLEME SAYFASI"))
        self.label_2.setText(_translate("Form_guncelle", "Öğrencinin Hangi Bilgisini Düzenlemek İstiyorsanız Seçin"))
        self.radioButton_tc.setText(_translate("Form_guncelle", "TC"))
        self.radioButton_isim.setText(_translate("Form_guncelle", " İSİM VEYA SINIF"))
