# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EkleSayfası.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_ekle(object):
    def setupUi(self, Form_ekle):
        Form_ekle.setObjectName("Form_ekle")
        Form_ekle.resize(400, 353)
        self.label = QtWidgets.QLabel(Form_ekle)
        self.label.setGeometry(QtCore.QRect(90, 10, 241, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form_ekle)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 151, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_tc = QtWidgets.QLineEdit(Form_ekle)
        self.lineEdit_tc.setGeometry(QtCore.QRect(10, 100, 191, 22))
        self.lineEdit_tc.setObjectName("lineEdit_tc")
        self.label_3 = QtWidgets.QLabel(Form_ekle)
        self.label_3.setGeometry(QtCore.QRect(10, 140, 121, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_isim = QtWidgets.QLineEdit(Form_ekle)
        self.lineEdit_isim.setGeometry(QtCore.QRect(10, 160, 191, 22))
        self.lineEdit_isim.setObjectName("lineEdit_isim")
        self.label_4 = QtWidgets.QLabel(Form_ekle)
        self.label_4.setGeometry(QtCore.QRect(10, 200, 121, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit_sinif = QtWidgets.QLineEdit(Form_ekle)
        self.lineEdit_sinif.setGeometry(QtCore.QRect(10, 230, 191, 22))
        self.lineEdit_sinif.setObjectName("lineEdit_sinif")
        self.pushButton_ekleEkle = QtWidgets.QPushButton(Form_ekle)
        self.pushButton_ekleEkle.setGeometry(QtCore.QRect(140, 280, 93, 28))
        self.pushButton_ekleEkle.setObjectName("pushButton_ekleEkle")
        self.label_5 = QtWidgets.QLabel(Form_ekle)
        self.label_5.setGeometry(QtCore.QRect(10, 80, 321, 16))
        self.label_5.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Form_ekle)
        QtCore.QMetaObject.connectSlotsByName(Form_ekle)

    def retranslateUi(self, Form_ekle):
        _translate = QtCore.QCoreApplication.translate
        Form_ekle.setWindowTitle(_translate("Form_ekle", "Form"))
        self.label.setText(_translate("Form_ekle", "ÖĞRENCİ EKLEME SAYFASI"))
        self.label_2.setText(_translate("Form_ekle", "TC kimlik numarası"))
        self.label_3.setText(_translate("Form_ekle", "İsim-soyisim"))
        self.label_4.setText(_translate("Form_ekle", "Sınıf"))
        self.pushButton_ekleEkle.setText(_translate("Form_ekle", "Ekle"))
