# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'İsimGüncelleme2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_isimGuncelle2(object):
    def setupUi(self, Form_isimGuncelle2):
        Form_isimGuncelle2.setObjectName("Form_isimGuncelle2")
        Form_isimGuncelle2.resize(400, 451)
        self.label = QtWidgets.QLabel(Form_isimGuncelle2)
        self.label.setGeometry(QtCore.QRect(20, 20, 361, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form_isimGuncelle2)
        self.label_2.setGeometry(QtCore.QRect(0, 80, 151, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_isimGuncelle = QtWidgets.QLineEdit(Form_isimGuncelle2)
        self.lineEdit_isimGuncelle.setGeometry(QtCore.QRect(0, 100, 241, 22))
        self.lineEdit_isimGuncelle.setObjectName("lineEdit_isimGuncelle")
        self.label_3 = QtWidgets.QLabel(Form_isimGuncelle2)
        self.label_3.setGeometry(QtCore.QRect(0, 140, 55, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_sinifGuncelle = QtWidgets.QLineEdit(Form_isimGuncelle2)
        self.lineEdit_sinifGuncelle.setGeometry(QtCore.QRect(0, 160, 113, 22))
        self.lineEdit_sinifGuncelle.setObjectName("lineEdit_sinifGuncelle")
        self.pushButton_isimSinifGuncelle = QtWidgets.QPushButton(Form_isimGuncelle2)
        self.pushButton_isimSinifGuncelle.setGeometry(QtCore.QRect(160, 320, 93, 28))
        self.pushButton_isimSinifGuncelle.setObjectName("pushButton_isimSinifGuncelle")
        self.label_4 = QtWidgets.QLabel(Form_isimGuncelle2)
        self.label_4.setGeometry(QtCore.QRect(0, 200, 381, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(Form_isimGuncelle2)
        self.lineEdit.setGeometry(QtCore.QRect(0, 240, 271, 22))
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(Form_isimGuncelle2)
        QtCore.QMetaObject.connectSlotsByName(Form_isimGuncelle2)

    def retranslateUi(self, Form_isimGuncelle2):
        _translate = QtCore.QCoreApplication.translate
        Form_isimGuncelle2.setWindowTitle(_translate("Form_isimGuncelle2", "Form"))
        self.label.setText(_translate("Form_isimGuncelle2", "ÖĞRENCİ İSİM VE SINIF GÜNCELLEME SAYFASI"))
        self.label_2.setText(_translate("Form_isimGuncelle2", "İsim-soyisim"))
        self.label_3.setText(_translate("Form_isimGuncelle2", "Sınıf"))
        self.pushButton_isimSinifGuncelle.setText(_translate("Form_isimGuncelle2", "Güncelle"))
        self.label_4.setText(_translate("Form_isimGuncelle2", "İsmi ve Sınıf bilgileri yeniden düzenlenecek öğrenci TC numarası"))
