# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SilSayfası.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_silme(object):
    def setupUi(self, Form_silme):
        Form_silme.setObjectName("Form_silme")
        Form_silme.resize(400, 279)
        self.label = QtWidgets.QLabel(Form_silme)
        self.label.setGeometry(QtCore.QRect(100, 10, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form_silme)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 141, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_siltc = QtWidgets.QLineEdit(Form_silme)
        self.lineEdit_siltc.setGeometry(QtCore.QRect(10, 140, 181, 22))
        self.lineEdit_siltc.setObjectName("lineEdit_siltc")
        self.pushButton_silSil = QtWidgets.QPushButton(Form_silme)
        self.pushButton_silSil.setGeometry(QtCore.QRect(150, 190, 93, 28))
        self.pushButton_silSil.setObjectName("pushButton_silSil")
        self.label_silUyariTc = QtWidgets.QLabel(Form_silme)
        self.label_silUyariTc.setGeometry(QtCore.QRect(10, 120, 321, 16))
        self.label_silUyariTc.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_silUyariTc.setText("")
        self.label_silUyariTc.setObjectName("label_silUyariTc")

        self.retranslateUi(Form_silme)
        QtCore.QMetaObject.connectSlotsByName(Form_silme)

    def retranslateUi(self, Form_silme):
        _translate = QtCore.QCoreApplication.translate
        Form_silme.setWindowTitle(_translate("Form_silme", "Form"))
        self.label.setText(_translate("Form_silme", "ÖĞRENCİ SİLME SAYFASI"))
        self.label_2.setText(_translate("Form_silme", "TC kimlik numarası"))
        self.pushButton_silSil.setText(_translate("Form_silme", "Sil"))
