# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tcGüncelleme.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_Tc(object):
    def setupUi(self, Form_Tc):
        Form_Tc.setObjectName("Form_Tc")
        Form_Tc.resize(400, 400)
        self.label = QtWidgets.QLabel(Form_Tc)
        self.label.setGeometry(QtCore.QRect(40, 10, 361, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form_Tc)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 351, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_tcDegisiceksim = QtWidgets.QLineEdit(Form_Tc)
        self.lineEdit_tcDegisiceksim.setGeometry(QtCore.QRect(10, 120, 291, 22))
        self.lineEdit_tcDegisiceksim.setObjectName("lineEdit_tcDegisiceksim")
        self.pushButton_devamet = QtWidgets.QPushButton(Form_Tc)
        self.pushButton_devamet.setGeometry(QtCore.QRect(150, 310, 93, 28))
        self.pushButton_devamet.setObjectName("pushButton_devamet")
        self.label_3 = QtWidgets.QLabel(Form_Tc)
        self.label_3.setGeometry(QtCore.QRect(10, 150, 281, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_sinifbilgi = QtWidgets.QLineEdit(Form_Tc)
        self.lineEdit_sinifbilgi.setGeometry(QtCore.QRect(10, 170, 201, 22))
        self.lineEdit_sinifbilgi.setObjectName("lineEdit_sinifbilgi")
        self.label_4 = QtWidgets.QLabel(Form_Tc)
        self.label_4.setGeometry(QtCore.QRect(10, 210, 201, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit_yenitc = QtWidgets.QLineEdit(Form_Tc)
        self.lineEdit_yenitc.setGeometry(QtCore.QRect(10, 240, 231, 22))
        self.lineEdit_yenitc.setObjectName("lineEdit_yenitc")

        self.retranslateUi(Form_Tc)
        QtCore.QMetaObject.connectSlotsByName(Form_Tc)

    def retranslateUi(self, Form_Tc):
        _translate = QtCore.QCoreApplication.translate
        Form_Tc.setWindowTitle(_translate("Form_Tc", "Form"))
        self.label.setText(_translate("Form_Tc", "ÖĞRENCİ TC BİLGİSİ GÜNCELLEME SAYFASI"))
        self.label_2.setText(_translate("Form_Tc", "TC numarasını değiştirmek istediğiniz öğrenci ismini giriniz"))
        self.pushButton_devamet.setText(_translate("Form_Tc", "Devam Et"))
        self.label_3.setText(_translate("Form_Tc", "Sınıf bilgisini giriniz"))
        self.label_4.setText(_translate("Form_Tc", "Yeni TC numarasını giriniz"))
